spring:
  application:
    name: fin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        use-new-id-generator-mappings: false
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:mysql://localhost:3306/fin
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
     
server:
  port: 8082
  servlet:
    context-path: "/fin" 

    
    
